export const PUBLIC_API_ENDPOINTS = [
  ['GET', '/health', 'Authenticated service health, provider readiness and strict RAG usability.'],
  ['GET', '/projects', 'List local workspaces.'],
  ['POST', '/projects', 'Create a local workspace.'],
  ['GET', '/projects/active', 'Read the active local project.'],
  ['POST', '/projects/active', 'Select the active project using an HTTP-only cookie.'],
  ['GET', '/projects/learning', 'Read reviewer-learning statistics scoped to the actor.'],
  ['GET', '/systems', 'List systems in the active workspace.'],
  ['POST', '/systems', 'Create a system in the active workspace.'],
  ['GET', '/systems/:id', 'Read one system.'],
  ['PATCH', '/systems/:id', 'Update a system.'],
  ['DELETE', '/systems/:id', 'Delete a system.'],
  ['GET', '/systems/:id/runs', 'List completed or partial runs for a system.'],
  ['GET', '/knowledge', 'List technical and corporate corpus files.'],
  ['POST', '/knowledge', 'Add a validated document to an approved corpus folder.'],
  ['GET', '/index', 'Read RAG index readiness and the active indexing job.'],
  ['POST', '/index', 'Start synchronization when the corpus fingerprint changed.'],
  ['GET', '/llm/credentials', 'Read credential configured/not-configured status.'],
  ['PUT', '/llm/credentials', 'Validate and save a locally managed cloud credential.'],
  ['DELETE', '/llm/credentials', 'Remove one locally managed credential.'],
  ['POST', '/llm/check', 'Run a bounded provider readiness check.'],
  ['POST', '/upload', 'Upload supporting material and return its upload_id and expiry.'],
  ['POST', '/analyze', 'Enqueue a pending analysis; the pipeline worker claims it.'],
  ['GET', '/analysis/:id/status', 'Read phase progress and terminal state.'],
  ['GET', '/analysis/:id/stream', 'Receive SSE progress; limited to five streams per actor and run.'],
  ['GET', '/analysis/:id/telemetry', 'Read bounded phase and agent telemetry.'],
  ['GET', '/results', 'List analyses with pagination and status filters.'],
  ['GET', '/results/:id', 'Return JSON, Markdown, CSV, PDF or reproducible inputs.'],
  ['PATCH', '/results/:id', 'Rename the register title, or archive/restore a finished run.'],
  ['GET', '/results/:id/diff?compareWith=:runId', 'Compare compatible runs for the same system.'],
  ['POST', '/results/:id/stop', 'Request cancellation of a running analysis.'],
  ['PATCH', '/results/:id/threats/:threatId', 'Update review state and notes.'],
  ['PATCH', '/results/:id/threats/:threatId/comments', 'Save analyst comments for one threat.'],
] as const
