import { StyleSheet } from '@react-pdf/renderer'

export const COLOR = {
  yellow: '#111111',
  yellowHover: '#333333',
  charcoal: '#111111',
  ink: '#333333',
  muted: '#666666',
  white: '#FFFFFF',
  canvas: '#EDF3EB',
  surface: '#F7FAF6',
  divider: '#DDE7DB',
  paleYellow: '#EAF2E8',
  green: '#335943',
  blue: '#666666',
  orange: '#333333',
  red: '#111111',
} as const

export const styles = StyleSheet.create({
  page: {
    paddingTop: 58,
    paddingRight: 42,
    paddingBottom: 46,
    paddingLeft: 42,
    backgroundColor: COLOR.white,
    color: COLOR.charcoal,
    fontFamily: 'Inter',
    fontSize: 9,
    lineHeight: 1.45,
  },
  pageLandscape: {
    paddingTop: 58,
    paddingRight: 32,
    paddingBottom: 42,
    paddingLeft: 32,
    backgroundColor: COLOR.white,
    color: COLOR.charcoal,
    fontFamily: 'Inter',
    fontSize: 8,
    lineHeight: 1.4,
  },
  header: {
    position: 'absolute',
    top: 22,
    left: 42,
    right: 42,
    height: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: COLOR.yellow,
    paddingBottom: 8,
  },
  headerLandscape: { left: 32, right: 32 },
  headerLogo: { width: 88, height: 22, objectFit: 'contain' },
  headerLabel: { color: COLOR.muted, fontSize: 7.5, letterSpacing: 0.7, textTransform: 'uppercase' },
  footerLeft: {
    position: 'absolute',
    bottom: 26,
    left: 42,
    color: COLOR.muted,
    fontSize: 7,
  },
  footerRight: {
    position: 'absolute',
    bottom: 26,
    right: 42,
    color: COLOR.muted,
    fontSize: 7,
    textAlign: 'right',
  },
  footerLeftLandscape: { left: 32 },
  footerRightLandscape: { right: 32 },
  cover: {
    padding: 52,
    backgroundColor: COLOR.white,
    color: COLOR.charcoal,
    fontFamily: 'Inter',
  },
  coverPanel: { position: 'absolute', top: 0, left: 0, right: 0, height: 520, backgroundColor: COLOR.canvas },
  coverOrb: { position: 'absolute', top: 55, right: -90, width: 390, height: 390, borderRadius: 195, borderWidth: 1, borderColor: '#CFDECC' },
  coverRail: { position: 'absolute', top: 0, left: 0, right: 0, height: 10, backgroundColor: COLOR.green },
  coverLogo: { width: 166, height: 48, objectFit: 'contain' },
  coverRule: { width: 80, height: 3, marginTop: 46, marginBottom: 24, backgroundColor: COLOR.green },
  coverKicker: { marginBottom: 12, color: COLOR.green, fontSize: 8, fontWeight: 700, letterSpacing: 1.4 },
  coverTitle: { maxWidth: 450, fontFamily: 'Archivo', fontSize: 30, fontWeight: 700, lineHeight: 1.08, letterSpacing: -0.6 },
  coverSubtitle: { marginTop: 14, maxWidth: 485, color: COLOR.muted, fontSize: 12, lineHeight: 1.45 },
  coverMetrics: { marginTop: 34, flexDirection: 'row', padding: 15, borderWidth: 1, borderColor: COLOR.divider, borderRadius: 10, backgroundColor: COLOR.white },
  coverMetric: { width: '25%', paddingTop: 4, paddingRight: 12 },
  coverMetricValue: { fontSize: 20, fontWeight: 700, color: COLOR.charcoal },
  coverMetricLabel: { marginTop: 3, color: COLOR.muted, fontSize: 7.5, letterSpacing: 0.7, textTransform: 'uppercase' },
  coverMeta: { position: 'absolute', left: 52, right: 52, bottom: 48, flexDirection: 'row', justifyContent: 'space-between' },
  coverMetaText: { color: COLOR.muted, fontSize: 8 },
  sectionTitle: { fontFamily: 'Archivo', fontSize: 19, fontWeight: 600, lineHeight: 1.2, letterSpacing: -0.25 },
  sectionIntro: { marginTop: 7, marginBottom: 18, maxWidth: 500, color: COLOR.muted, fontSize: 9.5, lineHeight: 1.5 },
  sectionRule: { width: 42, height: 1, marginTop: 10, marginBottom: 16, backgroundColor: COLOR.yellow },
  metricsRow: { flexDirection: 'row', marginBottom: 22, borderTopWidth: 1, borderBottomWidth: 1, borderColor: COLOR.divider },
  metric: { flexGrow: 1, paddingTop: 12, paddingBottom: 12, paddingRight: 12 },
  metricValue: { fontSize: 18, fontWeight: 700, lineHeight: 1.05 },
  metricLabel: { marginTop: 4, color: COLOR.muted, fontSize: 7, lineHeight: 1, letterSpacing: 0.65, textTransform: 'uppercase' },
  summaryBox: { padding: 16, backgroundColor: COLOR.surface, borderWidth: 1, borderColor: COLOR.divider, borderRadius: 8 },
  summaryText: { color: COLOR.ink, fontSize: 10, lineHeight: 1.55 },
  subheading: { marginTop: 20, marginBottom: 8, fontFamily: 'Archivo', fontSize: 12, fontWeight: 600 },
  table: { borderTopWidth: 1, borderLeftWidth: 1, borderColor: COLOR.divider },
  tableHeader: { flexDirection: 'row', backgroundColor: COLOR.white, color: COLOR.muted, borderBottomWidth: 1, borderBottomColor: COLOR.charcoal },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderColor: COLOR.divider, minHeight: 22 },
  tableCell: { paddingVertical: 4, paddingHorizontal: 7, borderRightWidth: 1, borderColor: COLOR.divider },
  tableHeadText: { fontSize: 7, fontWeight: 700, letterSpacing: 0.45, textTransform: 'uppercase' },
  tableText: { fontSize: 7.2, color: COLOR.ink, lineHeight: 1.3 },
  threat: { marginBottom: 9, padding: 11, borderWidth: 1, borderColor: COLOR.divider, borderRadius: 8, backgroundColor: COLOR.white },
  threatHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
  threatId: { width: 52, height: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: COLOR.charcoal },
  threatIdText: { color: COLOR.green, fontSize: 7.5, fontWeight: 700, lineHeight: 1.15 },
  threatTitle: { marginBottom: 4, fontSize: 10.5, fontWeight: 700, lineHeight: 1.2 },
  threatMeta: { marginBottom: 5, color: COLOR.muted, fontSize: 7, lineHeight: 1.35 },
  threatFootnote: { marginTop: 5, color: COLOR.muted, fontSize: 6.5 },
  badge: { width: 49, paddingVertical: 3, paddingHorizontal: 4, fontSize: 7, fontWeight: 700, textAlign: 'center', textTransform: 'uppercase' },
  factRow: { flexDirection: 'row', marginBottom: 5 },
  factLabel: { width: 82, color: COLOR.muted, fontSize: 7.5, fontWeight: 700, textTransform: 'uppercase' },
  factValue: { flex: 1, color: COLOR.ink, fontSize: 8.5 },
  bodyLabel: { marginTop: 5, marginBottom: 2, color: COLOR.muted, fontSize: 7, fontWeight: 700, letterSpacing: 0.45, textTransform: 'uppercase' },
  body: { color: COLOR.ink, fontSize: 8, lineHeight: 1.35 },
  mitigation: { marginTop: 6, padding: 8, backgroundColor: COLOR.surface, borderRadius: 5 },
  twoCol: { flexDirection: 'row', gap: 14 },
  column: { flex: 1 },
  evidenceEntry: { marginBottom: 11, paddingBottom: 10, borderBottomWidth: 1, borderColor: COLOR.divider },
  evidenceMeta: { color: COLOR.muted, fontSize: 7.5 },
  codeBlock: { marginTop: 8, padding: 12, backgroundColor: COLOR.charcoal, borderWidth: 1, borderColor: COLOR.charcoal, color: COLOR.surface, fontFamily: 'JetBrains Mono', fontSize: 7.5, lineHeight: 1.45 },
  warning: { marginBottom: 12, padding: 10, backgroundColor: COLOR.paleYellow, borderWidth: 1, borderColor: COLOR.orange, color: COLOR.ink },
  diagramLegend: { marginBottom: 8, paddingVertical: 7, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 10, backgroundColor: COLOR.white, borderWidth: 1, borderColor: COLOR.divider },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  legendText: { color: COLOR.ink, fontSize: 6.8 },
  legendBox: { width: 13, height: 9, backgroundColor: COLOR.canvas, borderWidth: 1, borderColor: COLOR.muted },
  legendExternal: { width: 15, height: 9, backgroundColor: COLOR.paleYellow, borderWidth: 1, borderColor: COLOR.yellowHover },
  legendStore: { width: 13, height: 9, backgroundColor: COLOR.white, borderWidth: 1, borderColor: COLOR.green },
  legendQueue: { width: 13, height: 9, backgroundColor: COLOR.white, borderWidth: 1, borderColor: COLOR.blue },
  legendFlow: { width: 20, height: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: COLOR.charcoal, borderWidth: 1, borderColor: COLOR.yellow },
  legendFlowText: { color: COLOR.white, fontSize: 6.2, fontWeight: 700, lineHeight: 1, textAlign: 'center' },
  legendZone: { width: 18, height: 11, backgroundColor: COLOR.surface, borderWidth: 1, borderStyle: 'dashed', borderColor: COLOR.divider },
  legendThreat: { color: COLOR.red, fontSize: 7, fontWeight: 700 },
  legendControl: { color: COLOR.green, fontSize: 7, fontWeight: 700 },
  diagramFrame: { padding: 4, backgroundColor: COLOR.white },
  diagramNote: { marginTop: 8, color: COLOR.muted, fontSize: 7.5 },
})

